version: '3.1'

services:
  postgres:
    image: 'postgres:12'
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: 123post
      POSTGRES_DB: websocket_db
    ports:
      - 5432:5432
    volumes:
      - ./.db_data:/var/lib/postgresql/data